# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b5815a1b-991a-4e87-8250-8eb41b5f1d03";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-b5815a1b-991a-4e87-8250-8eb41b5f1d03".device = "/dev/disk/by-uuid/b5815a1b-991a-4e87-8250-8eb41b5f1d03";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9647-7C9F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6debef84-20e2-45b6-ba71-812a1306739f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
