# A continuation prompt that displays two filled in arrows
continuation_prompt = "[](bright-black) "

# format = """$all"""
# right_format = """$cmd_duration$git_status$git_branch"""
# format = """$cmd_duration$git_status$git_branch$battery$all""" 

# Imprimir una nueva línea al inicio del prompt
add_newline = false

# Reemplaza el símbolo "❯" por "➜" del prompt
[character] 
#"[     ]" "[]" "[ ]" "[ ]" 
success_symbol = "[󰊠 ](bold fg:78)"
# success_symbol = "[ ](bold fg:78)"
#error_symbol = "[  🤯 ](bold red)"
# error_symbol = "[🤯 ](bold red)"
error_symbol = "[ ](bold red)"
vicmd_symbol = "[ ](bold green)"

[package]
disabled = true

[line_break]
disabled = false

[cmd_duration]
disabled = true
min_time = 500
format = "[󰄉 $duration]($style) "

[directory]
format = "[ $path]($style)[$read_only]($read_only_style) "
style = "bold #e39400"
truncation_length = 1
truncation_symbol = "…/"

[memory_usage]
disabled = false
threshold = 90
format = "[|](bold cyan) [$symbol ${ram_pct}]($style) "
symbol = "󰍛"
style = "bold purple"

[aws]
symbol = "󰸏 "

[rust]
format = '[$symbol]($style)'
