[shell.files]
starship = "~/.config/starship.toml"
ripgrep = "~/.config/.ripgreprc"

[bash]
depends = ["shell"]

[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/bash_profile" = "~/.bash_profile"
"bash/bash_logout" = "~/.bash_logout"

[zsh]
depends = ["shell"]

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/zshenv" = "~/.zshenv"

[rust.files]
rustup = "~/.rustup/settings.toml"

[alacritty.files]
alacritty = "~/.config/alacritty"

[neovim.files]
nvim = "~/.config/nvim"

[julia.files]
julia-startup = "~/.julia/config/startup.jl"

[tmux.files]
tmux = "~/.tmux.conf"
